Abhay Singh Rawat

Roll No.- 19/17026

In [112]:
import numpy as np
from numpy.linalg import eig
import sympy as sp

In [113]:
def Lege(n):
    xdx=np.zeros([n,n])
    d2x=np.zeros([n,n])
    x2d2x=np.zeros([n,n])
    L=np.zeros([n,n])
    for i in range(n):
        xdx[i,i]=(i)          #xd/dx matrix
        if i<(n-2):
            d2x[i,i+2]=(i+1)*(i+2)       #d2/dx2 matrix
            x2d2x[i+2,i+2]=d2x[i,i+2]    #x^2*d2/dx2 matrix
    #print(m2dx)
    #print(d2x)
    #print(x2d2x)
    
    L=d2x-x2d2x-2*xdx        #legendre operator
    print("Hence, our legendre operator will be: \n",L)
    #finding the polynomials
    
    e,pol=eig(L)
    """
    for i in range(n):
        if i==0 or i==1:
            print('the {} polynomial is :'.format(i),pol[:,i])
        else:
            print('the {} polynomial is :'.format(i),2**(i-2)*1.5*pol[:,i])
    """
    print('\n')
    x= sp.Symbol('x')
    for i in range(n):
        if i==0 or i==1:
            print('The {} polynomial is :'.format(i))
            leg=0
            for j in range(n):
                leg=leg+pol[j,i]*x**j      #summing all the terms
            print(leg)
        else:
            print('The {} polynomial is :'.format(i))
            leg=0
            for j in range(n):
                leg=leg+2**(i-2)*1.5*pol[j,i]*x**j
            print(leg)
        print('***********')



In [114]:
def Lag(n):
    dx=np.zeros([n,n])
    xd2x=np.zeros([n,n])
    xdx=np.zeros([n,n])
    L=np.zeros([n,n])
    for i in range(n):
        if i<n-1:
            dx[i,i+1]=i+1               #d/dx matrix
            xd2x[i,i+1]=(i)*(i+1)        #xd2/dx2 matrix
            
        xdx[i,i]=(i)          #xd/dx matrix
    
    #laguerrre operator
    L=xd2x+dx-xdx           
    print("Hence, our laguerre operator will be: \n",L)
    print('\n')
    
    #finding eigenvalue and eigenvector
    e,pol=eig(L)
    print("Laguerre eigenvales: ",e)
    x= sp.Symbol('x')
    for i in range(n):
          
        if i==0 or i==1:
            print('The {} polynomial is :'.format(i))
            lag=0
            for j in range(n):
                lag=lag+pol[j,i]*x**j      #summing all the terms
            print(lag)
            
        elif i==2 or i==3:
            print('The {} polynomial is :'.format(i))
            lag=0
            for j in range(n):
                lag=lag+i*pol[j,i]*x**j      #summing all the terms
            print(lag)
        else:
            print('The {} polynomial is :'.format(i))
            lag=0
            for j in range(n):
                lag=lag+(i+2)*pol[j,i]*x**j
            print(lag)
        print('***********')

          

In [115]:
n=int(input("No. of legendre polynomials you want: "))
Lege(n)
m=int(input("No. of laguerre polynomials you want: "))
Lag(m)

No. of legendre polynomials you want: 5
Hence, our legendre operator will be: 
 [[  0.   0.   2.   0.   0.]
 [  0.  -2.   0.   6.   0.]
 [  0.   0.  -6.   0.  12.]
 [  0.   0.   0. -12.   0.]
 [  0.   0.   0.   0. -20.]]


The 0 polynomial is :
1.00000000000000
***********
The 1 polynomial is :
1.0*x
***********
The 2 polynomial is :
1.42302494707577*x**2 - 0.474341649025257
***********
The 3 polynomial is :
2.57247877713763*x**3 - 1.54348726628258*x
***********
The 4 polynomial is :
4.5459231248636*x**4 - 3.89650553559737*x**2 + 0.389650553559737
***********
No. of laguerre polynomials you want: 5
Hence, our laguerre operator will be: 
 [[ 0.  1.  0.  0.  0.]
 [ 0. -1.  4.  0.  0.]
 [ 0.  0. -2.  9.  0.]
 [ 0.  0.  0. -3. 16.]
 [ 0.  0.  0.  0. -4.]]


Laguerre eigenvales:  [ 0. -1. -2. -3. -4.]
The 0 polynomial is :
1.00000000000000
***********
The 1 polynomial is :
0.707106781186547*x - 0.707106781186547
***********
The 2 polynomial is :
0.436435780471985*x**2 - 1.74574312188794*x +