In [2]:
import numpy as np
from numpy.linalg import qr

In [3]:
def qreig(A):
    condition = True
    i=0
    while condition:
        q , r = qr(A)
        A = np.dot(r,q)   #A[i+1]
        i=i+1
        if np.allclose(A, np.triu(A))==True:
            break
       
    print("No. of iterations :", i)
    print("The eigenvalues by QR METHOD are", np.diag(A))

In [4]:
#matrix input
A=np.array([[1,-2,8],[7,-7,6],[5,7,-8]])
print('matrix given :', A)
qreig(A)

matrix given : [[ 1 -2  8]
 [ 7 -7  6]
 [ 5  7 -8]]
No. of iterations : 142
The eigenvalues by QR METHOD are [-13.05115892  -6.76795298   5.8191119 ]


In [5]:
B=np.array([[4,-2,3,-7],[1,2,6,8],[8,5,1,-5],[-5,8,-5,3]])
print('matrix given :', B)
qreig(B)

matrix given : [[ 4 -2  3 -7]
 [ 1  2  6  8]
 [ 8  5  1 -5]
 [-5  8 -5  3]]
No. of iterations : 157
The eigenvalues by QR METHOD are [ 13.82986627 -10.24553385   8.91674962  -2.50108204]
